prefix = "/data"
stop-words = "/data/stop-words.txt"

dataset = "cranfield"
corpus = "line.toml"
index = "/data/idx/cranfield-idx"

query-judgements = "/data/cranfield/cranfield-qrels.txt"

[[analyzers]]
method = "ngram-word"
ngram = 1
filter = "default-unigram-chain"

[query-runner]
query-path = "/data/cranfield/cranfield-queries.txt"
query-id-start = 0
timeout = 60
