competition-name = "Search Engine Competition"

[[datasets]]
name = "cranfield"
config = "cranfield-config.toml"
top-k = 10
num-queries = 225
query-id-start = 1

[[datasets]]
name = "apnews"
config = "apnews-config.toml"
top-k = 10
num-queries = 100
query-id-start = 0
