competition-name = "Search Engine Competition"
timezone = "America/Chicago"

# URL for your gitlab instance
gitlab-url = "https://lab.textdata.org"

# hostname for the server running the mongodb instance; when using
# docker-compose this is "mongo", but when running it locally this is
# likely "localhost" or "127.0.0.1"
mongodb-host = "mongo"

[[datasets]]
name = "cranfield"
config = "/data/cranfield/config.toml"
top-k = 10
num-queries = 225
query-id-start = 1
weight = 0.2

[[datasets]]
name = "apnews"
config = "/data/apnews/config.toml"
top-k = 10
num-queries = 100
query-id-start = 0
weight = 0.6

[[datasets]]
name = "FacultyDataset"
config = "/data/FacultyDataset/config.toml"
top-k = 10
num-queries = 100
query-id-start = 0
weight = 0.2
